"""empty message

Revision ID: 28c9a5e3b29c
Revises: ca2f0eec2a7c
Create Date: 2021-08-03 18:07:45.656138

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '28c9a5e3b29c'
down_revision = 'ca2f0eec2a7c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('comment', 'pokemon_id')
    op.drop_column('comment', 'user_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comment', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('comment', sa.Column('pokemon_id', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
