"""empty message

Revision ID: d196d05d8108
Revises: d8191137110a
Create Date: 2021-08-03 18:47:44.840117

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd196d05d8108'
down_revision = 'd8191137110a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pokemon', sa.Column('name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pokemon', 'name')
    # ### end Alembic commands ###
