"""empty message

Revision ID: d8191137110a
Revises: 28c9a5e3b29c
Create Date: 2021-08-03 18:19:54.558241

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'd8191137110a'
down_revision = '28c9a5e3b29c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comment', sa.Column('pokemon_id', sa.Integer(), nullable=True))
    op.add_column('comment', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'comment', 'pokemon', ['pokemon_id'], ['id'])
    op.create_foreign_key(None, 'comment', 'person', ['user_id'], ['id'])
    op.drop_column('comment', 'date_created')
    op.drop_column('comment', 'date_updated')
    op.drop_column('person', 'created_on')
    op.drop_column('pokemon', 'date_created')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pokemon', sa.Column('date_created', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('person', sa.Column('created_on', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('comment', sa.Column('date_updated', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('comment', sa.Column('date_created', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'comment', type_='foreignkey')
    op.drop_constraint(None, 'comment', type_='foreignkey')
    op.drop_column('comment', 'user_id')
    op.drop_column('comment', 'pokemon_id')
    # ### end Alembic commands ###
